- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes
  become: true

- name: Update all packages to their latest version
  apt:
    name: "*"
    state: latest
  become: true

- name: Install apt dependencies
  apt:
    pkg:
    - build-essential
    - curl
    - python2
    - python-is-python2
    - git
    - libgtk2.0-dev
    - libgtkglext1-dev    
    - default-jre
    - p7zip-full
  become: true
